# Generated by Django 4.1.5 on 2023-01-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['id'], 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
    ]
